[theme]
primaryColor="#6B4F2B"         # Rich brown for accents/buttons
backgroundColor="#F8F3E6"      # Warm beige for main background
secondaryBackgroundColor="#EDE3D1" # Slightly darker beige for containers
textColor="#3E2C16"            # Dark brown for text
font="sans serif"